version: '3.8'
services:
  postgre:
    container_name: chat_postgre
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rabbitDB
    ports:
      - "5432:5432"

  rabbitmq3:
    container_name: rabbit_mq
    image: rabbitmq:3.8-management-alpine
    restart: "no"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    container_name: rabbit_redis
    restart: "no"
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  pgadmin:
    container_name: chat_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"